### ISSUE TITLE
模型推理输出是空

### ISSUE THREAD

**Issue by terryII** [THUDM/CogCoM#16]
hi，感谢你们所做的工作，我在使用`cli_demo_sat.py`的过程中输入问题`locate the helmet in this image`时，模型输出为空，通过debug发现，模型经过softmax后预测输出为结束符`</s>`，从而回答终止，但在输入问题`locate the helmet in this image.`时便会正常输出，两个问题只差一个标点符号，请问这是和模型的训练数据有关吗还是存在其他的问题？ @qijimrc

**Comment by qijimrc** [comment]
@terryII Hi Terry，感谢反馈。你描述的这个问题可能和训练数据有关，模型在SFT阶段所见到的instruction tuning数据大部分以`.`结尾，导致SFT后会有类似的prompt格式问题。我们会尝试在下个版本解决这个问题，谢谢。
