### ISSUE TITLE
com data中添加新的操作func

### ISSUE THREAD

**Issue by terryII** [THUDM/CogCoM#18]
hi,感谢你们开创性的工作，我注意到在cogcom中的steps中包含`grounding,crop_and_zoomin,counting,OCR`等func操作，根据项目需要，我希望在里面添加可以**检测关键点**的fun操作，如`pose`操作，其形式为`[x1,y1,x2,y2,kpt1,kpt2]`,其中，`kpt1`和`kpt2`为目标的关键点坐标，请问添加关键点func操作除在生成com数据时需要进行一定的修改，在**finetuning**时是否需要修改finetuning部分的代码？
@erjanmx @Sleepychord @cenyk1230 @Btlmd @1049451037

**Comment by qijimrc** [comment]
Hit @terryII , 感谢关注。添加你描述的新操作只需生成对应的数据，无需修改其他代码。
