### ISSUE TITLE
Where is the model?

### ISSUE THREAD

**Issue by DanielProkhorov** [THUDM/CogCoM#2]
The links within the readme doesn't lead to a model within the huggingface repo.

Please provide the correct links.

**Comment by qijimrc** [comment]
Hi,
Thanks for interesting. We have updated the checkpoints links in the huggingface repo for manually downloading. Additionally, you may automatically download the specific version of models through `cli_demo_sat.py`. We will continue to update new versions of our trained models, please contact us with any questions.
