### ISSUE TITLE
Grounding 回答图像中坐标有缩放吗？

### ISSUE THREAD

**Issue by AugWrite** [THUDM/CogCoM#24]
Q1：我将model返回的坐标（Model: [[453,526,661,618]]）画到cache image上，位置是错误的，且基本都分布在左上角。测试用例是提问画面中手机在哪里，请问是提问方式有问题，还是说图像（cache image）或 model返回的坐标 需要做缩放吗？

Q2：三个不同模型的权重具体区别只是功能吗？是说用了不同数据集训练吗？没太理解base、grounding、chat版本的区别都有哪些？

**Comment by zihui-debug** [comment]
> Q1：我将model返回的坐标（Model: [[453,526,661,618]]）画到cache image上，位置是错误的，且基本都分布在左上角。测试用例是提问画面中手机在哪里，请问是提问方式有问题，还是说图像（cache image）或 model返回的坐标 需要做缩放吗？
> 
> Q2：三个不同模型的权重具体区别只是功能吗？是说用了不同数据集训练吗？没太理解base、grounding、chat版本的区别都有哪些？

你好，请问这三个模型权重的区别是什么？
