### ISSUE TITLE
不能连续对话

### ISSUE THREAD

**Issue by theaimer09** [THUDM/CogCoM#9]
首先感谢作者开源
运行的demo_SAT，grounding和chat都尝试了，都是只能回答一次问题，第二次就报错
<img width="932" alt="image" src="https://github.com/THUDM/CogCoM/assets/103176666/a0ff9ec9-85a5-4a7d-a200-07260132fd80">

**Comment by qijimrc** [comment]
Hi，感谢你对我们工作的关注并指出这个问题。我已经在新版本中fix了这个bug（改动存在于`cli_demo_sat.py`），可以pull一下最新的commit。

**Comment by qijimrc** [comment]
> 首先感谢作者开源 运行的demo_SAT，grounding和chat都尝试了，都是只能回答一次问题，第二次就报错 <img alt="image" width="932" src="https://private-user-images.githubusercontent.com/103176666/310829804-a0ff9ec9-85a5-4a7d-a200-07260132fd80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzk4MzksIm5iZiI6MTcwOTk3OTUzOSwicGF0aCI6Ii8xMDMxNzY2NjYvMzEwODI5ODA0LWEwZmY5ZWM5LTg1YTUtNGE3ZC1hMjAwLTA3MjYwMTMyZmQ4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxMDE4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWE0NDUxZDM1YzM0YzUzMmQ4ODY1MDBlYzk1MzBmMWQ0YzE5MTQ5M2E2MjkzNTgwNjMxNTU2NjZjNzU0MjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jPA-9YTEUrVeVXjssqeylWWwIeMOIHM3b6Gj87gZRNU">

Hi，感谢你对我们工作的关注并指出这个问题。我已经在新版本中fix了这个bug（改动存在于cli_demo_sat.py），可以pull一下最新的commit。
